version: '3.8'

services:
  catalogdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  customerdb:
    image: postgres
  orderdb:
    image: mongo
  basketdb:
    image: redis
  userdb:
    image: mcr.microsoft.com/mssql/server:2019-latest 
  rabbitmq:
    image: rabbitmq:3.11.5-management
volumes:
  catalogdb_volume:
  customerdb_volume:
  orderdb_volume:
  userdb_volume:




    
  technomarket.services.catalog:
    container_name: c_catalogservice
    image: ${DOCKER_REGISTRY-}technomarketservicescatalog
    build:
      context: .
      dockerfile: Services/Catalog/TechnoMarket.Services.Catalog/Dockerfile





  technomarket.services.order:
    container_name: c_orderservice
    image: ${DOCKER_REGISTRY-}technomarketservicesorder
    build:
      context: .
      dockerfile: Services/Order/TechnoMarket.Services.Order/Dockerfile


  technomarket.services.customer:
    container_name: c_customerservice
    image: ${DOCKER_REGISTRY-}technomarketservicescustomer
    build:
      context: .
      dockerfile: Services/Customer/TechnoMarket.Services.Customer/Dockerfile





  technomarket.services.basket:
    container_name: c_basketservice
    image: ${DOCKER_REGISTRY-}technomarketservicesbasket
    build:
      context: .
      dockerfile: Services/Basket/TechnoMarket.Services.Basket/Dockerfile


  technomarket.services.photostock:
    container_name: c_photostockservice
    image: ${DOCKER_REGISTRY-}technomarketservicesphotostock
    build:
      context: .
      dockerfile: Services/PhotoStock/TechnoMarket.Services.PhotoStock/Dockerfile


  technomarket.gateway:
    container_name: c_apigateway
    image: ${DOCKER_REGISTRY-}technomarketgateway
    build:
      context: .
      dockerfile: Gateways/TechnoMarket.Gateway/Dockerfile


  technomarket.shopping.aggregator:
    container_name: c_shoppingaggregator
    image: ${DOCKER_REGISTRY-}technomarketshoppingaggregator
    build:
      context: .
      dockerfile: Gateways/TechnoMarket.Shopping.Aggregator/Dockerfile


  technomarket.web:
    container_name: c_shoppingweb
    image: ${DOCKER_REGISTRY-}technomarketweb
    build:
      context: .
      dockerfile: Frontends/TechnoMarket.Web/Dockerfile
