version: '3.4'

services:
  technomarket.services.order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  technomarket.services.customer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  technomarket.services.catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  technomarket.services.basket:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  technomarket.services.photostock:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  technomarket.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  technomarket.shopping.aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  technomarket.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

