version: '3.8'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - catalogdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=Password12* 
  customerdb:
    container_name: customerdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - customerdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=Password12* 
      - POSTGRES_DB=customerdb
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - orderdb_volume:/data/db 
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  userdb:
    container_name: userdb
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - userdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=Password12* 
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  catalog.api:
    container_name: catalog.api
    depends_on:
      - catalogdb
      - rabbitmq
    ports:
      - "5011:80"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
      - RabbitMQUrl:rabbitmq
      - "ConnectionStrings:SqlServer=Server=catalogdb,1433;Database=catalogdb;TrustServerCertificate=True;User=sa; Password=Password12*;"