version: '3.8'

services:
  catalogdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  customerdb:
    image: postgres
  orderdb:
    image: mongo
  basketdb:
    image: redis
  userdb:
    image: mcr.microsoft.com/mssql/server:2019-latest 
  rabbitmq:
    image: rabbitmq:3.11.5-management
volumes:
  catalogdb_volume:
  customerdb_volume:
  orderdb_volume:
  userdb_volume: