version: '3.4'

services:
  catalogdb:
    image: mongo

  technomarket.services.catalog:
    image: ${DOCKER_REGISTRY-}technomarketservicescatalog
    build:
      context: .
      dockerfile: Services/Catalog/TechnoMarket.Services.Catalog/Dockerfile

volumes:
  mongo_data: