// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoMarket.Services.Catalog.Data;

#nullable disable

namespace TechnoMarket.Services.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20221214144228_migV01")]
    partial class migV01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnoMarket.Services.Catalog.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a53c1fd9-2b60-405f-a73b-847c641214a1"),
                            Name = "Notebook"
                        },
                        new
                        {
                            Id = new Guid("c81bd97b-85ab-4cba-920a-73b5daab921f"),
                            Name = "Smart Phone"
                        });
                });

            modelBuilder.Entity("TechnoMarket.Services.Catalog.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CategoryId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageFile")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46a02782-f572-4c86-860e-8f908fc105ce"),
                            CategoryId = new Guid("a53c1fd9-2b60-405f-a73b-847c641214a1"),
                            CreatedAt = new DateTime(2022, 12, 14, 17, 42, 28, 322, DateTimeKind.Local).AddTicks(3918),
                            Description = "12th gen Intel® Core™ i9 processor,32 GB memory,1 TB SSD storage",
                            ImageFile = "asuszenbook.jpeg",
                            Name = "Asus Zenbook",
                            Price = 40000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("7723714d-be34-438a-9f9e-57463d94dd5b"),
                            CategoryId = new Guid("c81bd97b-85ab-4cba-920a-73b5daab921f"),
                            CreatedAt = new DateTime(2022, 12, 14, 17, 42, 28, 322, DateTimeKind.Local).AddTicks(3935),
                            Description = "512 GB Capacity,6,7' display,A15 Bionic chip,Ceramic shield front, glass back and aluminium design",
                            ImageFile = "appleiphone14.jpeg",
                            Name = "Iphone 14 Plus",
                            Price = 30000m,
                            Stock = 50
                        });
                });

            modelBuilder.Entity("TechnoMarket.Services.Catalog.Models.ProductFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Width")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProductFeatures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46a02782-f572-4c86-860e-8f908fc105ce"),
                            Color = "Black",
                            Height = "12'",
                            Weight = "2.5 kg",
                            Width = "15.3'"
                        },
                        new
                        {
                            Id = new Guid("7723714d-be34-438a-9f9e-57463d94dd5b"),
                            Color = "Purple",
                            Height = "6.33'",
                            Weight = "0.25 kg",
                            Width = "3.07'"
                        });
                });

            modelBuilder.Entity("TechnoMarket.Services.Catalog.Models.Product", b =>
                {
                    b.HasOne("TechnoMarket.Services.Catalog.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechnoMarket.Services.Catalog.Models.ProductFeature", b =>
                {
                    b.HasOne("TechnoMarket.Services.Catalog.Models.Product", "Product")
                        .WithOne("Feature")
                        .HasForeignKey("TechnoMarket.Services.Catalog.Models.ProductFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechnoMarket.Services.Catalog.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechnoMarket.Services.Catalog.Models.Product", b =>
                {
                    b.Navigation("Feature");
                });
#pragma warning restore 612, 618
        }
    }
}
